# specify vers
version: 2.1

# defile orbs
orbs:
  node: circleci/node@5.0.0

# define jobs
jobs: 
  # define jb name
  install-dependencies:
    # executer
    docker: 
      - image: cimg/node:18.20.0
    # steps
    steps:
       - checkout
       - run:
           # define cmd
          name: install app depe..
          command: npm i

  build:
    # executer
    docker: 
      - image: cimg/node:18.20.0
    # steps
    steps:
      - checkout
      - run: 
      # define cmd
          name: build app
          command: npm run build

    deploy:
    # executer
      docker: 
        - image: cimg/node:18.20.0
    # steps
      steps:
        - checkout
        - run: 
        # define cmd
            name: deploy app
            command: npm run deploy

# defilne workflow
workflows: 
  # define name
  install-build-deploy: 
    jobs: 
    # list jobs in sequence
      - install-dependencies
      - build:
          # tell the exec to run the above job first
          requires: 
            - install-dependencies
      - deploy: 
          # tell the exec to run the above job first
          requires: 
            - build
          filters: 
            branches: 
              - only: main


