version: 2.1
orbs:
  node: circleci/node@5.0.0
jobs:
  build:
    docker:
      - image: cimg/node:18.2.0
    steps:
      - checkout
      - run:
          name: Install site dependencies
          command: npm install
      - run:
          name: Build site
          command: npm run build
      - run:
          name: Deploy site to netlify
          command: npm run deploy

workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
